### ISSUE TITLE
Login Personas

### ISSUE THREAD

**Issue by rvelasquezrojas** [Maximo91/divertrip-frontend#23]
Permitir el acceso a las personas, una vez se ingrese debe acceder a la vista de "Lista eventos".
# flujo de trabajo
- [ ] Crear view en template 
- [ ] Crear controller en controllers.js
- [ ] Recibir datos del servidor con verificacion
- [ ] Crear localStorage
- [ ] Persona logeada se dirige a la vista opciones de menu

**Comment by sunsettheory** [comment]
Cuando se permita el acceso a las personas, la vista a mostrar debe ser las opciones de menú disponibles para "Personas" y no la vista de "Lista eventos", ya que si no se quiere ver eventos y se quiere ver otra opción se estaría cargando de manera inicial información que no es de interés del usuario.

**Comment by rvelasquezrojas** [comment]
Debido a que solo significa una barrera para un turista, esta funcionalidad ha sido eliminada
